OCPBUGS-7845 fix: changes the way the version is shown
openshift/oc-mirror pull request #599
Opened 2023-04-04 13:24 UTC by aguidirh

# Description

This issue fix OCPBUGS-7845 by changing the way version is shown in oc-mirror. 

A new flag --info was added to keep the old mechanism responsible to show the entire version schema.

Fixes OCPBUGS-7845

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

To show the long version:

```
./bin/oc-mirror version
Client Version: v0.2.0-alpha.1-103-g6943ced
```

To show the short version:

```
./bin/oc-mirror version --short
Client Version: v0.2.0
```

To show the entire version schema:

```
./bin/oc-mirror version --info
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-103-g6943ced", GitCommit:"6943ced8", GitTreeState:"dirty", BuildDate:"2023-04-04T11:52:15Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-04 14:51 UTC, lmzuccarelli commented
/lgtm

2023-04-04 14:51 UTC, lmzuccarelli commented
@aguidirh - nice and simple fix

2023-04-05 10:44 UTC, soltysh requested changes
/hold
You should not introduce yet another option just to print version, but rather try to minimize the current output to short, both oc and kubectl (in-progress) report this by default:
```
$ oc version 
Client Version: 4.14.0-0.ci-2023-04-04-023533
Kustomize Version: v4.5.7
Server Version: 4.13.0-rc.2
Kubernetes Version: v1.26.2+dc93b13
```
alternatively you have the `--output` option which will give you the full json or yaml.

2023-04-05 14:22 UTC, soltysh approved these changes
/lgtm
/approve
/hold cancel

2023-04-05 14:33 UTC, merged

2023-04-06 08:03 UTC, aguidirh commented
/jira refresh